### ISSUE TITLE
A question about search

### ISSUE THREAD

**Issue by luyingwei80** [Sarjuuk/aowow#416] opened 2024-05-26 13:25 UTC
I found a problem, which should be my case here, where no matter what content I enter in the search box, it shows no search results. I don't know where the problem may be.

**Comment by Sarjuuk** [comment] 2024-05-26 18:34
https://github.com/Sarjuuk/aowow?tab=readme-ov-file#troubleshooting
Item #8 maybe?

**Comment by luyingwei80** [comment] 2024-05-27 08:19
It should be slightly different from the situation described in the eighth item, but the displayed situation is indeed consistent with the one described in the eighth item, because I did not add any custom information to the database, only used the most primitive database. I tried searching in Simplified Chinese and couldn't get any feedback on anything I searched for, but searching for English names did show it. Does this mean that currently, the search function only supports English?

**Comment by Sarjuuk** [comment] 2024-05-27 12:58
![grafik](https://github.com/Sarjuuk/aowow/assets/848030/bbb0eb5d-00a9-4ef7-acef-0c05ee8e2577)
it should work generally.

can you check your DB if the *_loc4 (thats zhCN) columns have data? (or *_loc0 if you are searching in english)

**Comment by luyingwei80** [comment] 2024-05-27 13:37
Sorry, due to my limited understanding of database applications, sometimes the questions I ask may seem very childish and superficial to you. Please forgive me. Also, my English is poor, and many of them are translated through Google. If there are any words that do not convey meaning, please forgive me.

Are you referring to "* _loc4" as being viewed directly in a table in the database? Can you tell which table it is located in? 

After reading your screenshot, I also tried searching with "barren land" and I am glad that it can indeed display the same search results as your screenshot.

But I also found another problem. If I search for "灵风", the system will still prompt that there are no search results, but when I search for "灵风头巾", I can still find it. It seems that wildcard search is not supported.
![image](https://github.com/Sarjuuk/aowow/assets/67801546/59c908f8-c6e7-4f57-9510-ce8014270eee)
![image](https://github.com/Sarjuuk/aowow/assets/67801546/56278d1b-a84c-4806-b77b-e302765ebdc4)

**Comment by Sarjuuk** [comment] 2024-05-27 15:36
oh no D:

The problem is, that the seach ignores words with fewer than 3 letters. Which makes sense as you don't want to search for gibberish inputs or concatenations that are very common. 

except

this doesn't work for languages where one "letter" is a word in itself.

**Comment by Sarjuuk** [comment] 2024-05-27 15:54
should be fixed in 33b3e945b4e38c61b614404cc085035f8ef04a6f

**Comment by luyingwei80** [comment] 2024-05-27 16:03
Your update is too fast^_^, I will go and update it. Also, after updating the code, is it still possible to use the "PHP aowow -- setup" command? I feel that the entire process takes quite a long time, and it seems that the system has been completely re executed.

**Comment by Sarjuuk** [comment] 2024-05-27 16:16
use `php aowow --update`
when it's purely code changes like in this case, it's not required.

**Comment by luyingwei80** [comment] 2024-05-27 16:22
Just now during the installation process, there was a prompt:
```error
16: 08:16 [WARN] GlobalStrings.lua not found for selected locale enus
[c] Continue any way? [r] Etry? [a] Bort?:
```
Although the installation process can continue, I'm not sure if there will be any other impact, or is it just a case on my end? Just for your reference.

**Comment by luyingwei80** [comment] 2024-05-27 16:29
Thank you very much. The issue with this search has been resolved^_^

**Comment by Sarjuuk** [comment] 2024-05-27 16:30
GlobalStrings.lua contains the aliasses for emotes. As you don't use the enUS locale it should be irrelevant for you.

**Closed by Sarjuuk** 2024-05-27 16:30 UTC
Labels: Bug, Support
