### ISSUE TITLE
NPCs have no abilities

### ISSUE THREAD

**Issue by wodim** [Sarjuuk/aowow#182] opened 2019-05-14 17:01 UTC
I've tried many NPCs and none show any abilities.

**Comment by Aokromes** [comment] 2020-01-11 11:45
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=6570

**Comment by Sarjuuk** [comment] 2020-02-23 18:22
cannot reproduce. maybe fixed in-between?

**Comment by wodim** [comment] 2020-02-23 18:23
https://db.rising-gods.de/?npc=6570 <- compare this to the link posted above

**Comment by wodim** [comment] 2020-02-23 18:24
https://db.rising-gods.de/?npc=677 vs https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=677, etc

**Comment by Sarjuuk** [comment] 2020-02-23 18:51
ah, i see now.

Rising Gods did not wish to publish SAI, so everything related to SAI is gone. 
This is not a bug of Aowow.

**Closed by Sarjuuk** 2020-02-23 18:51 UTC
